#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Setting up frontend configuration from deployed stack...${NC}"

# Get the stack name (default: ResumeTailorStack)
STACK_NAME="${1:-ResumeTailorStack}"
REGION="${AWS_REGION:-us-east-1}"

echo -e "${BLUE}📡 Fetching outputs from CloudFormation stack: ${STACK_NAME}${NC}"

# Fetch stack outputs
OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query 'Stacks[0].Outputs' \
  --output json)

if [ -z "$OUTPUTS" ] || [ "$OUTPUTS" == "null" ]; then
  echo -e "${RED}❌ Failed to fetch stack outputs. Is the stack deployed?${NC}"
  exit 1
fi

# Extract values
USER_POOL_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="UserPoolId") | .OutputValue')
USER_POOL_CLIENT_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="UserPoolClientId") | .OutputValue')
IDENTITY_POOL_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="IdentityPoolId") | .OutputValue')
BUCKET_NAME=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="BucketName") | .OutputValue')
STATE_MACHINE_ARN=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="StateMachineArn") | .OutputValue')

# Validate all values were found
if [ -z "$USER_POOL_ID" ] || [ -z "$USER_POOL_CLIENT_ID" ] || [ -z "$IDENTITY_POOL_ID" ] || [ -z "$BUCKET_NAME" ] || [ -z "$STATE_MACHINE_ARN" ]; then
  echo -e "${RED}❌ Missing required outputs from stack${NC}"
  exit 1
fi

# Create frontend .env file
ENV_FILE="frontend/.env"
echo -e "${BLUE}📝 Writing configuration to ${ENV_FILE}${NC}"

cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/setup-frontend-config.sh
# DO NOT COMMIT THIS FILE - it contains environment-specific values

VITE_AWS_REGION=${REGION}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
VITE_IDENTITY_POOL_ID=${IDENTITY_POOL_ID}
VITE_BUCKET_NAME=${BUCKET_NAME}
VITE_STATE_MACHINE_ARN=${STATE_MACHINE_ARN}
EOF

echo -e "${GREEN}✅ Frontend .env file created${NC}"

# Create config for CloudFront deployment script
DEPLOY_CONFIG="frontend/.deploy-config.json"
echo -e "${BLUE}📝 Writing deployment config to ${DEPLOY_CONFIG}${NC}"

cat > "$DEPLOY_CONFIG" << EOF
{
  "region": "${REGION}",
  "userPoolId": "${USER_POOL_ID}",
  "userPoolClientId": "${USER_POOL_CLIENT_ID}",
  "identityPoolId": "${IDENTITY_POOL_ID}",
  "bucketName": "${BUCKET_NAME}",
  "stateMachineArn": "${STATE_MACHINE_ARN}"
}
EOF

echo -e "${GREEN}✅ Deployment config created${NC}"

# Display summary
echo ""
echo -e "${GREEN}🎉 Configuration complete!${NC}"
echo ""
echo -e "${BLUE}Configuration values:${NC}"
echo "  Region: ${REGION}"
echo "  User Pool: ${USER_POOL_ID}"
echo "  User Pool Client: ${USER_POOL_CLIENT_ID}"
echo "  Identity Pool: ${IDENTITY_POOL_ID}"
echo "  Bucket: ${BUCKET_NAME}"
echo "  State Machine: ${STATE_MACHINE_ARN}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  • Local dev: cd frontend && npm run dev"
echo "  • Deploy to CloudFront: ./deploy-frontend.sh"
